# Generated by Django 4.0.3 on 2022-09-26 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_num', models.IntegerField(verbose_name='零件号')),
                ('part_name', models.CharField(max_length=32, verbose_name='零件描述')),
                ('part_quantity', models.IntegerField(verbose_name='装配个数')),
                ('part_level', models.IntegerField(verbose_name='所属层次')),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_num', models.IntegerField(verbose_name='物料号')),
                ('m_name', models.CharField(max_length=32, verbose_name='物料名称')),
                ('m_way', models.SmallIntegerField(choices=[(1, '生产'), (2, '采购')], verbose_name='调配方式')),
                ('m_wastage', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='损耗率')),
                ('work_time', models.IntegerField(verbose_name='作业提前期(/天)')),
            ],
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_c', models.IntegerField(verbose_name='工序库存')),
                ('materiel_c', models.IntegerField(verbose_name='资材库存')),
                ('cash_m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERPapp.materiel', verbose_name='库存物料')),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_num', models.IntegerField(verbose_name='调配基准编号')),
                ('a_code', models.IntegerField(verbose_name='调配区代码')),
                ('materiel_time', models.IntegerField(verbose_name='配料提前期(/天)')),
                ('manufacture_time', models.IntegerField(verbose_name='供应商提前期(/天)')),
                ('child_m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_m', to='ERPapp.materiel', verbose_name='子物料')),
                ('father_m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='father_m', to='ERPapp.materiel', verbose_name='父物料')),
            ],
        ),
    ]
