# Generated by Django 4.0.3 on 2022-09-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERPapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='a_code',
            field=models.CharField(max_length=32, verbose_name='调配区代码'),
        ),
    ]
