# Generated by Django 4.0.3 on 2022-09-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERPapp', '0002_alter_allocation_a_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MPS_name', models.CharField(max_length=32, verbose_name='产品名称')),
                ('MPS_num', models.IntegerField(verbose_name='数量')),
                ('MPS_time', models.DateField(verbose_name='完工日期')),
            ],
        ),
    ]
