# Generated by Django 4.0.3 on 2022-10-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERPapp', '0003_mps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='资产类说明')),
                ('guid_mark', models.CharField(max_length=16, null=True, verbose_name='资产类方向')),
                ('guid_num', models.IntegerField(null=True, verbose_name='资产类汇总序号')),
                ('asset_name', models.CharField(max_length=32, null=True, verbose_name='变量名')),
            ],
        ),
    ]
